#!/bin/bash

OUTPUT=${1?Usage: $0 output_directory}

set -e -x -o pipefail

mkdir -p "$OUTPUT/cache"

: Create channel files
tar -cJf "$OUTPUT/nixexprs.tar.xz" ./*.nix \
    --transform "s,^,${PWD##*/}/," \
    --owner=0 --group=0 --mtime="1970-01-01 00:00:00 UTC"
touch "$OUTPUT/index.html"
printf 'https://www.lpenz.org/nixpkgs-lpenz/cache' > "$OUTPUT/binary-cache-url"

: Build
nix-build

: Populate cache
export NIX_SECRET_KEY_FILE="$PWD/nix-cache-priv-key.pem"
echo "$NIX_CACHE_PRIV_KEY" > "$NIX_SECRET_KEY_FILE"
nix sign-paths -k "$NIX_SECRET_KEY_FILE"
nix copy --to "file:///$PWD/$OUTPUT/cache"
nix path-info --store "file:///$PWD/$OUTPUT/cache" --json | json_pp
